version: '3.9'

services:
    portainer:
        image: portainer/portainer
        container_name: dev_management
        env_file:
          - ./.env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        ports:
            - ${PORTAINER_EXTERNAL_PORT}:9000
        command: -H unix:///var/run/docker.sock
        restart: always

volumes:
    portainer_data:
